version: "3.7"
services:
  database:
    image: mysql
    container_name: backend-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mid_fullstack_test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
    restart: always
    networks:
      - app_network
  backend:
    build: ./Backend
    working_dir: /application
    container_name: backend-server
    volumes:
      - ./Backend:/var/www/html
    ports:
      - "8001:80"
    networks:
      - app_network
    depends_on:
      - database
  frontend:
    build: ./Frontend
    container_name: frontend-server
    ports:
      - "3000:81"
    depends_on:
      -   backend
    networks:
      - app_network
networks:
  app_network:
