version: "3.7"
services:
  database:
    image: mysql
    container_name: backend-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mid_fullstack_test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
    restart: always
  backend:
    build: ./Backend
    working_dir: /application
    container_name: backend-server
    volumes:
      - ./Backend:/application
  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./Backend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"